// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var brunchScaffold, create, initSkeleton, scaffolt, sysPath, test, watch;

  initSkeleton = require('init-skeleton');

  scaffolt = require('scaffolt');

  sysPath = require('path');

  watch = require('./watch');

  test = require('./test');

  create = function(options) {
    var _ref, _ref1;

    if ((_ref = options.skeleton) == null) {
      options.skeleton = sysPath.join(__dirname, '..', 'skeletons', 'brunch-with-chaplin');
    }
    return initSkeleton(options.skeleton, (_ref1 = options.rootPath) != null ? _ref1 : '.');
  };

  brunchScaffold = function(revert, options) {
    options.revert = revert;
    options.parentPath = options.parentDir;
    return scaffolt(options.type, options.name, options);
  };

  module.exports = {
    "new": create,
    build: watch.bind(null, false),
    watch: watch.bind(null, true),
    generate: brunchScaffold.bind(null, false),
    destroy: brunchScaffold.bind(null, true),
    test: test
  };

}).call(this);
